export interface ArxivCategory {
  id: string;
  name: string;
  group: string;
}

export const ARXIV_CATEGORIES: ArxivCategory[] = [
  // Computer Science
  { id: 'cs.AI', name: 'Artificial Intelligence', group: 'Computer Science' },
  { id: 'cs.AR', name: 'Hardware Architecture', group: 'Computer Science' },
  { id: 'cs.CC', name: 'Computational Complexity', group: 'Computer Science' },
  { id: 'cs.CE', name: 'Computational Engineering, Finance, and Science', group: 'Computer Science' },
  { id: 'cs.CG', name: 'Computational Geometry', group: 'Computer Science' },
  { id: 'cs.CL', name: 'Computation and Language (NLP)', group: 'Computer Science' },
  { id: 'cs.CR', name: 'Cryptography and Security', group: 'Computer Science' },
  { id: 'cs.CV', name: 'Computer Vision and Pattern Recognition', group: 'Computer Science' },
  { id: 'cs.CY', name: 'Computers and Society', group: 'Computer Science' },
  { id: 'cs.DB', name: 'Databases', group: 'Computer Science' },
  { id: 'cs.DC', name: 'Distributed, Parallel, and Cluster Computing', group: 'Computer Science' },
  { id: 'cs.DL', name: 'Digital Libraries', group: 'Computer Science' },
  { id: 'cs.DM', name: 'Discrete Mathematics', group: 'Computer Science' },
  { id: 'cs.DS', name: 'Data Structures and Algorithms', group: 'Computer Science' },
  { id: 'cs.ET', name: 'Emerging Technologies', group: 'Computer Science' },
  { id: 'cs.FL', name: 'Formal Languages and Automata Theory', group: 'Computer Science' },
  { id: 'cs.GL', name: 'General Literature', group: 'Computer Science' },
  { id: 'cs.GR', name: 'Graphics', group: 'Computer Science' },
  { id: 'cs.GT', name: 'Computer Science and Game Theory', group: 'Computer Science' },
  { id: 'cs.HC', name: 'Human-Computer Interaction', group: 'Computer Science' },
  { id: 'cs.IR', name: 'Information Retrieval', group: 'Computer Science' },
  { id: 'cs.IT', name: 'Information Theory', group: 'Computer Science' },
  { id: 'cs.LG', name: 'Machine Learning', group: 'Computer Science' },
  { id: 'cs.LO', name: 'Logic in Computer Science', group: 'Computer Science' },
  { id: 'cs.MA', name: 'Multiagent Systems', group: 'Computer Science' },
  { id: 'cs.MM', name: 'Multimedia', group: 'Computer Science' },
  { id: 'cs.MS', name: 'Mathematical Software', group: 'Computer Science' },
  { id: 'cs.NA', name: 'Numerical Analysis', group: 'Computer Science' },
  { id: 'cs.NE', name: 'Neural and Evolutionary Computing', group: 'Computer Science' },
  { id: 'cs.NI', name: 'Networking and Internet Architecture', group: 'Computer Science' },
  { id: 'cs.OH', name: 'Other Computer Science', group: 'Computer Science' },
  { id: 'cs.OS', name: 'Operating Systems', group: 'Computer Science' },
  { id: 'cs.PF', name: 'Performance', group: 'Computer Science' },
  { id: 'cs.PL', name: 'Programming Languages', group: 'Computer Science' },
  { id: 'cs.RO', name: 'Robotics', group: 'Computer Science' },
  { id: 'cs.SC', name: 'Symbolic Computation', group: 'Computer Science' },
  { id: 'cs.SD', name: 'Sound', group: 'Computer Science' },
  { id: 'cs.SE', name: 'Software Engineering', group: 'Computer Science' },
  { id: 'cs.SI', name: 'Social and Information Networks', group: 'Computer Science' },
  { id: 'cs.SY', name: 'Systems and Control', group: 'Computer Science' },
  // Mathematics
  { id: 'math.AC', name: 'Commutative Algebra', group: 'Mathematics' },
  { id: 'math.AG', name: 'Algebraic Geometry', group: 'Mathematics' },
  { id: 'math.AP', name: 'Analysis of PDEs', group: 'Mathematics' },
  { id: 'math.AT', name: 'Algebraic Topology', group: 'Mathematics' },
  { id: 'math.CA', name: 'Classical Analysis and ODEs', group: 'Mathematics' },
  { id: 'math.CO', name: 'Combinatorics', group: 'Mathematics' },
  { id: 'math.CT', name: 'Category Theory', group: 'Mathematics' },
  { id: 'math.CV', name: 'Complex Variables', group: 'Mathematics' },
  { id: 'math.DG', name: 'Differential Geometry', group: 'Mathematics' },
  { id: 'math.DS', name: 'Dynamical Systems', group: 'Mathematics' },
  { id: 'math.FA', name: 'Functional Analysis', group: 'Mathematics' },
  { id: 'math.GM', name: 'General Mathematics', group: 'Mathematics' },
  { id: 'math.GN', name: 'General Topology', group: 'Mathematics' },
  { id: 'math.GR', name: 'Group Theory', group: 'Mathematics' },
  { id: 'math.GT', name: 'Geometric Topology', group: 'Mathematics' },
  { id: 'math.HO', name: 'History and Overview', group: 'Mathematics' },
  { id: 'math.IT', name: 'Information Theory', group: 'Mathematics' },
  { id: 'math.KT', name: 'K-Theory and Homology', group: 'Mathematics' },
  { id: 'math.LO', name: 'Logic', group: 'Mathematics' },
  { id: 'math.MG', name: 'Metric Geometry', group: 'Mathematics' },
  { id: 'math.MP', name: 'Mathematical Physics', group: 'Mathematics' },
  { id: 'math.NA', name: 'Numerical Analysis', group: 'Mathematics' },
  { id: 'math.NT', name: 'Number Theory', group: 'Mathematics' },
  { id: 'math.OA', name: 'Operator Algebras', group: 'Mathematics' },
  { id: 'math.OC', name: 'Optimization and Control', group: 'Mathematics' },
  { id: 'math.PR', name: 'Probability', group: 'Mathematics' },
  { id: 'math.QA', name: 'Quantum Algebra', group: 'Mathematics' },
  { id: 'math.RA', name: 'Rings and Algebras', group: 'Mathematics' },
  { id: 'math.RT', name: 'Representation Theory', group: 'Mathematics' },
  { id: 'math.SG', name: 'Symplectic Geometry', group: 'Mathematics' },
  { id: 'math.SP', name: 'Spectral Theory', group: 'Mathematics' },
  { id: 'math.ST', name: 'Statistics Theory', group: 'Mathematics' },
  // Statistics
  { id: 'stat.AP', name: 'Applications', group: 'Statistics' },
  { id: 'stat.CO', name: 'Computation', group: 'Statistics' },
  { id: 'stat.ME', name: 'Methodology', group: 'Statistics' },
  { id: 'stat.ML', name: 'Machine Learning', group: 'Statistics' },
  { id: 'stat.OT', name: 'Other Statistics', group: 'Statistics' },
  { id: 'stat.TH', name: 'Statistics Theory', group: 'Statistics' },
  // Physics
  { id: 'physics.acc-ph', name: 'Accelerator Physics', group: 'Physics' },
  { id: 'physics.ao-ph', name: 'Atmospheric and Oceanic Physics', group: 'Physics' },
  { id: 'physics.app-ph', name: 'Applied Physics', group: 'Physics' },
  { id: 'physics.atm-clus', name: 'Atomic and Molecular Clusters', group: 'Physics' },
  { id: 'physics.atom-ph', name: 'Atomic Physics', group: 'Physics' },
  { id: 'physics.bio-ph', name: 'Biological Physics', group: 'Physics' },
  { id: 'physics.chem-ph', name: 'Chemical Physics', group: 'Physics' },
  { id: 'physics.class-ph', name: 'Classical Physics', group: 'Physics' },
  { id: 'physics.comp-ph', name: 'Computational Physics', group: 'Physics' },
  { id: 'physics.data-an', name: 'Data Analysis, Statistics and Probability', group: 'Physics' },
  { id: 'physics.ed-ph', name: 'Physics Education', group: 'Physics' },
  { id: 'physics.flu-dyn', name: 'Fluid Dynamics', group: 'Physics' },
  { id: 'physics.gen-ph', name: 'General Physics', group: 'Physics' },
  { id: 'physics.geo-ph', name: 'Geophysics', group: 'Physics' },
  { id: 'physics.hist-ph', name: 'History and Philosophy of Physics', group: 'Physics' },
  { id: 'physics.ins-det', name: 'Instrumentation and Detectors', group: 'Physics' },
  { id: 'physics.med-ph', name: 'Medical Physics', group: 'Physics' },
  { id: 'physics.optics', name: 'Optics', group: 'Physics' },
  { id: 'physics.plasm-ph', name: 'Plasma Physics', group: 'Physics' },
  { id: 'physics.pop-ph', name: 'Popular Physics', group: 'Physics' },
  { id: 'physics.soc-ph', name: 'Physics and Society', group: 'Physics' },
  { id: 'physics.space-ph', name: 'Space Physics', group: 'Physics' },
  // Condensed Matter
  { id: 'cond-mat.dis-nn', name: 'Disordered Systems and Neural Networks', group: 'Condensed Matter' },
  { id: 'cond-mat.mes-hall', name: 'Mesoscale and Nanoscale Physics', group: 'Condensed Matter' },
  { id: 'cond-mat.mtrl-sci', name: 'Materials Science', group: 'Condensed Matter' },
  { id: 'cond-mat.other', name: 'Other Condensed Matter', group: 'Condensed Matter' },
  { id: 'cond-mat.quant-gas', name: 'Quantum Gases', group: 'Condensed Matter' },
  { id: 'cond-mat.soft', name: 'Soft Condensed Matter', group: 'Condensed Matter' },
  { id: 'cond-mat.stat-mech', name: 'Statistical Mechanics', group: 'Condensed Matter' },
  { id: 'cond-mat.str-el', name: 'Strongly Correlated Electrons', group: 'Condensed Matter' },
  { id: 'cond-mat.supr-con', name: 'Superconductivity', group: 'Condensed Matter' },
  // Astrophysics
  { id: 'astro-ph.CO', name: 'Cosmology and Nongalactic Astrophysics', group: 'Astrophysics' },
  { id: 'astro-ph.EP', name: 'Earth and Planetary Astrophysics', group: 'Astrophysics' },
  { id: 'astro-ph.GA', name: 'Astrophysics of Galaxies', group: 'Astrophysics' },
  { id: 'astro-ph.HE', name: 'High Energy Astrophysical Phenomena', group: 'Astrophysics' },
  { id: 'astro-ph.IM', name: 'Instrumentation and Methods for Astrophysics', group: 'Astrophysics' },
  { id: 'astro-ph.SR', name: 'Solar and Stellar Astrophysics', group: 'Astrophysics' },
  // High Energy Physics
  { id: 'hep-ex', name: 'High Energy Physics - Experiment', group: 'High Energy Physics' },
  { id: 'hep-lat', name: 'High Energy Physics - Lattice', group: 'High Energy Physics' },
  { id: 'hep-ph', name: 'High Energy Physics - Phenomenology', group: 'High Energy Physics' },
  { id: 'hep-th', name: 'High Energy Physics - Theory', group: 'High Energy Physics' },
  // Quantum Physics & GR
  { id: 'quant-ph', name: 'Quantum Physics', group: 'Quantum Physics' },
  { id: 'gr-qc', name: 'General Relativity and Quantum Cosmology', group: 'Quantum Physics' },
  { id: 'nucl-ex', name: 'Nuclear Experiment', group: 'Quantum Physics' },
  { id: 'nucl-th', name: 'Nuclear Theory', group: 'Quantum Physics' },
  { id: 'nlin.AO', name: 'Adaptation and Self-Organizing Systems', group: 'Nonlinear Sciences' },
  { id: 'nlin.CD', name: 'Chaotic Dynamics', group: 'Nonlinear Sciences' },
  { id: 'nlin.CG', name: 'Cellular Automata and Lattice Gases', group: 'Nonlinear Sciences' },
  { id: 'nlin.PS', name: 'Pattern Formation and Solitons', group: 'Nonlinear Sciences' },
  { id: 'nlin.SI', name: 'Exactly Solvable and Integrable Systems', group: 'Nonlinear Sciences' },
  // Electrical Engineering & Systems
  { id: 'eess.AS', name: 'Audio and Speech Processing', group: 'Electrical Engineering' },
  { id: 'eess.IV', name: 'Image and Video Processing', group: 'Electrical Engineering' },
  { id: 'eess.SP', name: 'Signal Processing', group: 'Electrical Engineering' },
  { id: 'eess.SY', name: 'Systems and Control', group: 'Electrical Engineering' },
  // Quantitative Biology
  { id: 'q-bio.BM', name: 'Biomolecules', group: 'Quantitative Biology' },
  { id: 'q-bio.CB', name: 'Cell Behavior', group: 'Quantitative Biology' },
  { id: 'q-bio.GN', name: 'Genomics', group: 'Quantitative Biology' },
  { id: 'q-bio.MN', name: 'Molecular Networks', group: 'Quantitative Biology' },
  { id: 'q-bio.NC', name: 'Neurons and Cognition', group: 'Quantitative Biology' },
  { id: 'q-bio.OT', name: 'Other Quantitative Biology', group: 'Quantitative Biology' },
  { id: 'q-bio.PE', name: 'Populations and Evolution', group: 'Quantitative Biology' },
  { id: 'q-bio.QM', name: 'Quantitative Methods', group: 'Quantitative Biology' },
  { id: 'q-bio.SC', name: 'Subcellular Processes', group: 'Quantitative Biology' },
  { id: 'q-bio.TO', name: 'Tissues and Organs', group: 'Quantitative Biology' },
  // Quantitative Finance & Economics
  { id: 'q-fin.CP', name: 'Computational Finance', group: 'Quantitative Finance' },
  { id: 'q-fin.EC', name: 'Economics', group: 'Quantitative Finance' },
  { id: 'q-fin.GN', name: 'General Finance', group: 'Quantitative Finance' },
  { id: 'q-fin.MF', name: 'Mathematical Finance', group: 'Quantitative Finance' },
  { id: 'q-fin.PM', name: 'Portfolio Management', group: 'Quantitative Finance' },
  { id: 'q-fin.PR', name: 'Pricing of Securities', group: 'Quantitative Finance' },
  { id: 'q-fin.RM', name: 'Risk Management', group: 'Quantitative Finance' },
  { id: 'q-fin.ST', name: 'Statistical Finance', group: 'Quantitative Finance' },
  { id: 'q-fin.TR', name: 'Trading and Market Microstructure', group: 'Quantitative Finance' },
  { id: 'econ.EM', name: 'Econometrics', group: 'Economics' },
  { id: 'econ.GN', name: 'General Economics', group: 'Economics' },
  { id: 'econ.TH', name: 'Theoretical Economics', group: 'Economics' },
];
